repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: [--config, .prettierrc, --write]
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        types: [file]
        files: \.(svelte|js|ts)$
        entry: npm run lint
